apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: application-replicas
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v1
  template:
    metadata:
      labels:
        app: employees
        version: v1
    spec:
      containers:
        - name: appnikh
          image: 260735819899.dkr.ecr.us-east-1.amazonaws.com/webapp:v0.1
          ports:
            - containerPort: 8080
          env: 
            - name: DBHOST
              value: databaseservice.sqldb.svc.cluster.local
            - name: DBUSER
              value: root
            - name: DBPORT
              value: "3306"
            - name: DBPWD
              value: nikh1234