apiVersion: v1
kind: Service
metadata:
  name: applicationservice
  labels:
    name: appnikh
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
  selector:
    name: appnikh