apiVersion: v1
kind: Pod
metadata:
  name: mysql_db
  labels: 
    name: mysql_db
spec:
  containers:
  - name: mysql_db
    image: 260735819899.dkr.ecr.us-east-1.amazonaws.com/appdatabase:v0.1
    ports: 
    - containerPort: 3306
    env: 
     - name: MYSQL_ROOT_PASSWORD
       value: nikh1234
